apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api
spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: {{ .Release.Name }}-api

  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-api

    spec:
      containers:
        - name: cloudforge-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: 5000

          readinessProbe:
            httpGet:
              path: /ready
              port: 5000

          livenessProbe:
            httpGet:
              path: /health
              port: 5000
